# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '14.4'

target 'airpollution' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON' 
  # Pods for airpollution
  # pod 'SwiftyJSON', '~> 4.2'
end
